#!/usr/bin/env bash
# sensitive-guard pre-commit hook
# Managed by sensitive-guard-cli — https://npm.im/sensitive-guard-cli
# Do not edit this file manually; run: npx sensitive-guard-cli init

RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'

REPO_ROOT=$(git rev-parse --show-toplevel)
SENSITIVE_TERMS_FILE="$REPO_ROOT/.sensitive-terms"
FOUND=0

STAGED_FILES=$(git diff --cached --name-only --diff-filter=d)
[ -z "$STAGED_FILES" ] && exit 0

echo ""

# ── helpers ──────────────────────────────────────────────────────────────────

_check() {
  local flag="$1" label="$2" pattern="$3" file="$4"
  local matches
  matches=$(git diff --cached -U0 "$file" 2>/dev/null \
    | grep "^+" | grep -v "^+++" \
    | grep "$flag" "$pattern" 2>/dev/null)
  [ -z "$matches" ] && return
  echo -e "${RED}[BLOCKED] ${label} in: ${YELLOW}${file}${NC}"
  echo "$matches" | head -3 | sed 's/^/  /'
  echo ""
  FOUND=1
}

check_exact() { _check "-E"  "$1" "$2" "$3"; }
check_icase() { _check "-iE" "$1" "$2" "$3"; }

_custom_term_pattern() {
  local term="$1"
  local pattern

  # Treat every regex metacharacter as text. Only '*' is a wildcard.
  pattern=$(printf '%s' "$term" \
    | sed -e 's/[][\\.^$()+?{|}]/\\&/g' -e 's/\*/.*/g')

  # Without a wildcard at an edge, require a whole-word boundary there.
  [[ "$term" == \** ]] || pattern="(^|[^[:alnum:]_])${pattern}"
  [[ "$term" == *\* ]] || pattern="${pattern}([^[:alnum:]_]|$)"

  printf '%s' "$pattern"
}

# ── built-in patterns ────────────────────────────────────────────────────────

for file in $STAGED_FILES; do

  # --- exact / format-based ---
  check_exact "Private Key"    "-----BEGIN (RSA |EC |DSA |OPENSSH )?PRIVATE KEY"         "$file"
  check_exact "AWS Access Key" "AKIA[0-9A-Z]{16}"                                         "$file"
  check_exact "Anthropic Key"  "sk-ant-[A-Za-z0-9_-]{20,}"                               "$file"
  check_exact "OpenAI Key"     "sk-[A-Za-z0-9]{32,}"                                      "$file"
  check_exact "Google API Key" "AIza[0-9A-Za-z_-]{35}"                                    "$file"
  check_exact "GitHub Token"   "gh[pousr]_[A-Za-z0-9]{36,}"                               "$file"
  check_exact "Slack Token"    "xox[baprs]-[A-Za-z0-9-]{10,}"                             "$file"
  check_exact "JWT Token"      "eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+"      "$file"

  # --- case-insensitive assignment patterns ---
  SEP="[[:space:]]*[=:][[:space:]]*['\"]?"
  check_icase "AWS Secret Key"    "(aws_secret_access_key|aws_secret_key)${SEP}[A-Za-z0-9/+=]{40}"        "$file"
  check_icase "API Key"           "(api_key|apikey|api-key)${SEP}[A-Za-z0-9_-]{20,}"                      "$file"
  check_icase "Token"             "(access_token|auth_token|secret_token|bearer_token)${SEP}[A-Za-z0-9_.-]{20,}" "$file"
  check_icase "Password"          "(password|passwd|pwd)${SEP}.{8,}"                                      "$file"
  check_icase "Secret"            "(client_secret|app_secret)${SEP}[A-Za-z0-9_-]{10,}"                   "$file"
  check_icase "Connection String" "(mongodb|postgresql|mysql|redis)://[^@[:space:]]+:[^@[:space:]]+@"      "$file"

done

# ── custom terms from .sensitive-terms ───────────────────────────────────────

if [ -f "$SENSITIVE_TERMS_FILE" ]; then
  while IFS= read -r term || [ -n "$term" ]; do
    term="${term%$'\r'}"
    [[ -z "$term" || "$term" == \#* ]] && continue

    case_sensitive=0
    if [[ "$term" == case:* ]]; then
      case_sensitive=1
      term="${term#case:}"
    fi

    if [ -z "$term" ]; then
      echo -e "${YELLOW}[WARN] Ignoring empty custom term after 'case:' prefix.${NC}"
      continue
    fi

    pattern=$(_custom_term_pattern "$term")

    for file in $STAGED_FILES; do
      if [ "$case_sensitive" -eq 1 ]; then
        matches=$(git diff --cached -U0 "$file" 2>/dev/null \
          | grep "^+" | grep -v "^+++" \
          | grep -E "$pattern" 2>/dev/null)
        match_mode="whole-word/wildcard, case-sensitive"
      else
        matches=$(git diff --cached -U0 "$file" 2>/dev/null \
          | grep "^+" | grep -v "^+++" \
          | grep -iE "$pattern" 2>/dev/null)
        match_mode="whole-word/wildcard, case-insensitive"
      fi
      [ -z "$matches" ] && continue
      echo -e "${RED}[BLOCKED] Custom term '${YELLOW}${term}${RED}' (${match_mode}) in: ${YELLOW}${file}${NC}"
      echo "$matches" | head -3 | sed 's/^/  /'
      echo ""
      FOUND=1
    done
  done < "$SENSITIVE_TERMS_FILE"
fi

# ── result ───────────────────────────────────────────────────────────────────

if [ "$FOUND" -eq 1 ]; then
  echo -e "${RED}Commit blocked: sensitive information detected.${NC}"
  echo -e "  Edit ${YELLOW}.sensitive-terms${NC} to manage custom blocked terms."
  echo -e "  Run  ${YELLOW}npx sensitive-guard-cli list${NC} to see all active rules."
  echo -e "  Use  ${YELLOW}git commit --no-verify${NC} to bypass (use with care)."
  echo ""
  exit 1
fi

echo -e "${GREEN}[OK] No sensitive information detected.${NC}"
exit 0
